services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - postgres
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
