package io.meyer1994;

public enum DiscordEvent {
    ON_MESSAGE,
    ON_MESSAGE_UPDATE,
    ON_MESSAGE_DELETE,
    ON_MESSAGE_BULK_DELETE,
    ON_MESSAGE_REACTION_ADD,
    ON_MESSAGE_REACTION_REMOVE,
    ON_MESSAGE_REACTION_REMOVE_ALL,
    ON_MESSAGE_REACTION_REMOVE_EMOJI,
}
