= Discord Component
:doctitle: Discord
:shortname: discord
:artifactid: camel-discord
:description: Receive Discord events and send, reply to, or react to Discord messages through a configured JDA client.
:since: 0.0
:supportlevel: Preview

The Discord component integrates Apache Camel with the https://github.com/discord-jda/JDA[JDA] Discord API library.

== URI format

[source,text]
----
discord:name[?options]
----

The `name` path value identifies the endpoint. The `client` option supplies the JDA client used by the endpoint.

== Authentication and client setup

Create and start a JDA client in the application, then make it available to the endpoint through the `client` option or Camel registry. The Discord component does not create or manage the bot client lifecycle.

== Consumer

Consumers register a listener for the event selected by the `event` option. Supported event names are documented in the generated endpoint metadata. Incoming exchanges contain the Discord event as the body and expose event details through the component headers.

Example:

[source,java]
----
from("discord:messages?event=onMessageReceived&client=#jda")
    .log("Received message ${body}");
----

== Producer

Producers execute the operation selected by the `operation` option. The message body and component headers provide the values required by the selected operation.

Example:

[source,java]
----
from("direct:send")
    .to("discord:messages?operation=sendMessage&client=#jda");
----

== Component options

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
include::partial$component-endpoint-headers.adoc[]
// component options: END

== See also

* https://jda.wiki/[JDA documentation]
* https://discord.com/developers/docs/intro[Discord developer documentation]
