apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: postgres
    jsonData:
      database: postgres
      sslmode: disable
      postgresVersion: 1600
      timescaleDB: false
