app.twitch.channels=aspaszin,kaicenat,hasanabi,jynxzi

spring.application.name=camel-twitch-example

spring.sql.init.mode=always
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=

logging.level.org.apache.camel=INFO

camel.component.openai.api-key=${OPENAI_API_KEY:}
camel.component.openai.model=${OPENAI_MODEL:gpt-4.1-mini}
camel.component.openai.embedding-model=${OPENAI_EMBEDDING_MODEL:text-embedding-3-small}
camel.component.openai.lazy-start-producer=true