status = warn
name = CamelTwitchExample

appender.console.type = Console
appender.console.name = CONSOLE
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss} %-5level %logger - %msg%n

rootLogger.level = INFO
rootLogger.appenderRefs.console.ref = CONSOLE

logger.camel.name = org.apache.camel
logger.camel.level = DEBUG
logger.camel.additivity = false
logger.camel.appenderRefs.console.ref = CONSOLE
