CREATE TABLE IF NOT EXISTS twitch_chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id VARCHAR(64),
    channel_name VARCHAR(25) NOT NULL,
    user_id VARCHAR(64),
    user_name VARCHAR(25),
    message_id VARCHAR(64),
    message VARCHAR(4096) NOT NULL,
    raw_event CLOB NOT NULL,
    ai_category VARCHAR(512),
    embedding CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE twitch_chat_messages
    ADD COLUMN IF NOT EXISTS ai_category VARCHAR(512);

ALTER TABLE twitch_chat_messages
    ADD COLUMN IF NOT EXISTS embedding CLOB;
