CREATE TABLE IF NOT EXISTS twitch_event_chat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id TEXT,
    event_time TIMESTAMPTZ,
    channel_id TEXT,
    channel_name TEXT NOT NULL,
    user_id TEXT,
    user_name TEXT,
    display_name TEXT,
    message TEXT NOT NULL,
    subscriber_months INTEGER NOT NULL DEFAULT 0,
    subscription_tier INTEGER NOT NULL DEFAULT 0,
    nonce TEXT,
    raw_event JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_twitch_event_chat_channel_time
    ON twitch_event_chat (channel_name, event_time);

CREATE INDEX IF NOT EXISTS idx_twitch_event_chat_channel_user
    ON twitch_event_chat (channel_name, user_name, event_time);

CREATE INDEX IF NOT EXISTS idx_twitch_event_chat_user_time
    ON twitch_event_chat (user_name, event_time);

CREATE INDEX IF NOT EXISTS idx_twitch_event_chat_user_channel
    ON twitch_event_chat (user_name, channel_name, event_time);

CREATE INDEX IF NOT EXISTS idx_twitch_event_chat_event_time
    ON twitch_event_chat (event_time);

CREATE INDEX IF NOT EXISTS idx_twitch_event_chat_created_at
    ON twitch_event_chat (created_at, event_time);

CREATE INDEX IF NOT EXISTS idx_twitch_event_chat_subscriber_months
    ON twitch_event_chat (subscriber_months, event_time);

CREATE INDEX IF NOT EXISTS idx_twitch_event_chat_subscription_tier
    ON twitch_event_chat (subscription_tier, event_time);

CREATE INDEX IF NOT EXISTS idx_twitch_event_chat_display_name
    ON twitch_event_chat (display_name, event_time);
