package io.meyer1994.example;

import java.sql.Connection;
import java.sql.Statement;

import javax.sql.DataSource;

import org.apache.camel.main.Main;
import org.h2.jdbcx.JdbcDataSource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.JDABuilder;
import net.dv8tion.jda.api.requests.GatewayIntent;

public class App {
    private static final Logger LOG = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) throws Exception {
        String token = System.getenv("DISCORD_TOKEN");

        if (token == null || token.isBlank()) {
            throw new IllegalStateException("DISCORD_TOKEN must be set before starting the example");
        }

        JDA jda = JDABuilder.createDefault(token)
                .enableIntents(
                        GatewayIntent.MESSAGE_CONTENT,
                        GatewayIntent.DIRECT_MESSAGES)
                .build()
                .awaitReady();

        DataSource ds = createDataSource();
        initializeDatabase(ds);

        Main main = new Main(App.class);
        main.bind("client", jda);
        main.bind("dataSource", ds);

        try {
            main.run(args);
        } finally {
            jda.shutdown();
        }
    }

    private static DataSource createDataSource() {
        JdbcDataSource dataSource = new JdbcDataSource();

        /*
         * DB_CLOSE_DELAY=-1 keeps the in-memory database alive after
         * individual JDBC connections are closed.
         */
        dataSource.setURL(
                "jdbc:h2:mem:camel-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE");
        dataSource.setUser("sa");
        dataSource.setPassword("");

        return dataSource;
    }

    private static void initializeDatabase(DataSource dataSource)
            throws Exception {

        try (Connection connection = dataSource.getConnection();
                Statement statement = connection.createStatement()) {

            statement.execute("""
                    create table if not exists event (
                        id bigint generated by default as identity primary key,
                        data text not null
                    )
                    """);
        }
    }

}
